apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  # Set to true to use volume mounts instead of volume claims
  localDeploy: true
  # The container URI to pull (currently needs to be public)
  image: ghcr.io/flux-framework/demo-lammps-mpi:flux-sched-focal-v0.22.0
  # The main flux command to run - the job will exit after
  command: mpirun -x PATH -np 2 --map-by socket lmp -v x 2 -v y 2 -v z 2 -in in.reaxc.hns -nocite
  # You can set the working directory if your container WORKDIR is not correct.
  workingDir: /home/flux/examples/reaxff/HNS
  # Always pull the image (if you are updating the image between runs, set to true)!
  pullAlways: false
  # Number of pods to create for MiniCluster
  size: 4
  # Diagnostics runs flux commands for diagnostics, and a final sleep command
  # That makes it easy for you to shell into the pod to look around
  diagnostics: false
  # Deadline in seconds, if not set there is no deadline
  # deadlineSeconds: 100
  # Name of an already created ImagePullSecret for the image specfied above
  # imagePullSecret: flux-image-secret
