---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: fluxsetups.flux-framework.org
spec:
  group: flux-framework.org
  names:
    kind: FluxSetup
    listKind: FluxSetupList
    plural: fluxsetups
    singular: fluxsetup
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FluxSetup is the Schema for the fluxes setups API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FluxSetupSpec defines the desired state of Flux
            properties:
              broker:
                description: Broker describes the broker config (and any other attributes
                  we can eventually add)
                properties:
                  config:
                    description: Data holds the configuration file data
                    type: string
                required:
                - config
                type: object
              cert:
                description: CurveCert is just a placeholder for what eventually will
                  be done by the operator
                properties:
                  config:
                    description: Data holds the configuration file data
                    type: string
                required:
                - config
                type: object
              hostfile:
                description: TODO these three things should eventually be properly
                  mapped into go structs CurveCert is just a placeholder for what
                  eventually will be done by the operator
                properties:
                  config:
                    description: Data holds the configuration file data
                    type: string
                required:
                - config
                type: object
              size:
                description: Size of the statefulset replias
                format: int32
                type: integer
            required:
            - broker
            - cert
            - hostfile
            type: object
          status:
            description: FluxSetupStatus defines the observed state of a FluxSetup
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
