name: build flux-operator

on:
  pull_request: {}
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  # Only build arm image on merge, takes too long otherwise
  build-arm:
    if: (github.event_name != 'pull_request')    
    runs-on: ubuntu-latest
    name: make and build arm
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.20
    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Add custom buildx ARM builder
      run: |
       docker buildx create --name armbuilder
       docker buildx use armbuilder
       docker buildx inspect --bootstrap

    - name: Deploy Container
      run: make arm-deploy

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [docker]

    name: make and build ${{ matrix.command }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.20
    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Container
      run: make ${{ matrix.command }}-build

    - name: Deploy Container
      if: (github.event_name != 'pull_request')
      run: make ${{ matrix.command }}-push
