name: docs flux-operator
on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Create conda environment
      run: conda create --quiet -c conda-forge --name fluxdocs sphinx-material

    - name: Generate Docs
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"        
        root=$PWD
        source activate fluxdocs
        git clone https://github.com/flux-framework/flux-operator /tmp/operator
        cd /tmp/operator/docs
        pip install -r requirements.txt
        make html
        echo
        echo "ls"
        ls
        echo
        echo "ls _build/html"
        ls _build/html
        mv $root/.git _build/html/.git
        rm -rf $root
        mv /tmp/operator/docs/_build/html $root
        cd ${root}
        echo "ls $root"        
        ls .
        touch .nojekyll
        git add .nojekyll || echo "Already added"
        git add .
        ls .

    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6 # v4.4.1
      with:
        branch: gh-pages
        folder: .
